feat: 404페이지 구현
beyondDevelops/AnimalTalk pull request #84
Opened 2022-12-17 06:21 UTC by IntHyun

# feat: 404페이지 구현

## 🍀 무엇을 위한 PR인가요?
- [x] 기능 추가 : 404페이지 구현하였습니다. 
- [ ] 디자인 : 
- [ ] 리팩토링 :
- [ ] 문서 수정 :
- [ ] 버그 수정 :
- [ ] 기타 : 

## ⚠️ 삭제된 파일 

- 없음

## ✂️ 수정된 파일

- src/pages/NotFound/NotFound.jsx

## 📝 생성된 파일

- 없음

## 📢 스크린샷

## 📌 제안 사항

- [링크](이슈 링크 달아주세요)

## 🍀 Close Issue Number
close: #83

2022-12-17 12:11 UTC, GreattitJY requested changes
article 태그만 바꿔주면 될 거 같습니다. 고생하셨습니다!

2022-12-17 12:11 UTC, GreattitJY commented on src/pages/NotFound/NotFound.jsx
> +    <article className="page">
article 요소에 h1 태그는 적절하지 않은 거 같아요. article은 보통 위젯처럼 다른 페이지의 하위 요소로 들어가서 h1 보다는 h2~h6을 쓰는 게 더 적절할 거 같습니다. 그리고 404 페이지는 하나의 페이지이기 때문에 article로 쓰지 않고 div로 가져가도 될 거 같아요.

2022-12-18 02:31 UTC, July249 approved these changes
수고하셨습니다! 추가 내용은 리뷰 내용을 확인하여 주세요~

2022-12-18 02:31 UTC, July249 commented on src/pages/NotFound/NotFound.jsx
> +    <article className="page">
전체적인 레이아웃을 가져 가기 때문에 index.css에 적용한 main 요소 스타일을 이용하면 될 것 같습니다.

article 대신 main요소 하나만 적용하는 것은 어떨까요? 물론 main을 가장 밖으로 가져간다면 heading 요소는 h1으로 가져가는 것도 괜찮을 것 같습니다.

2022-12-19 00:38 UTC, IntHyun commented
머지하겠습니다!

2022-12-19 00:39 UTC, merged